theme = "er"
canonifyurls = true
relativeURLs = true
prettyURLs = false
baseURL = "https://isaFos.github.io/hawaii-pulse"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

languageCode = "en-us"
title = "Hawaii Weekly Pulse"
toc = false

[permalinks]
    post = "/:year/:month/:day/:slug/"
[[menu.main]]
    name = "State"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Counties"
    url = "/counties/"
    weight = 2
[[menu.main]]
	parent = "Counties"
	name = "Hawaii"
	url = "/hawaii"
[[menu.main]]
	parent = "Counties"
	name = "Honolulu"
	url = "/honolulu"
[[menu.main]]
	parent = "Counties"
	name = "Kauai"
	url = "/kauai"
[[menu.main]]
	parent = "Counties"
	name = "Maui"
	url = "/maui"
[[menu.main]]
  name = "About"
  url = "/about"

[params]
    description = "A website built through Hugo and blogdown."
    sitename = "Food insecurity"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
